
spring:
  application:
    name: social-media-demo
  data:
    mongodb:
      uri: mongodb+srv://markfieldsuk:z4iFMp8cPFXw5hvC@cluster0.rsy1hrv.mongodb.net/social-media-demo

server:
  port: 8080
  servlet:
    context-path: /social-media/api